# Generated by Django 5.1.2 on 2024-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_to_table", "0002_extractedtext"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedtext",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
